### PR TITLE
fix: pass pull request header and footer options to merge plugin

### LINKED ISSUE #2142: Merge plugin does not use `pull-request-header` and `pull-request-footer` config values
#### Environment details

  - OS: `Darwin pieholden-m1.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64 arm Darwin`
  - Node.js version: `20.7.0`
  - npm version: `10.2.3`
  - `release-please` version: `16.3.0`

#### Steps to reproduce

  1. Set `pull-request-header` and `pull-request-footer` to any string value
  2. Set `separate-pull-requests` to `false`
  3. Use `release-please` to create a PR with multiple components
  4. Observe that the default header and footer are part of the PR

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by lukekarrys**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2142  🦕

### Details

This works by looping through `repositoryConfig` and getting the first set value for both `pullRequestHeader` and `pullRequestFooter`. This means they could possibly come from different components in a manifest release.

### Alternate Solutions

I thought about only using config values from `repositoryConfig[ROOT_PROJECT_PATH]`. I didn't have strong feelings either way so I went with the solution I felt would be less surprising. But I'd be open to reworking the PR to this alternate solution.

### CODE REVIEW

**Review by chingor13 — CHANGES_REQUESTED** [review]
Thanks for this! The feature seems reasonable, but this one has a bit more complex logic and could use a unit test to demonstrate the example and to ensure we don't regress in the future.

**Comment by lukekarrys** [comment]
Thanks @chingor13! I added a test case where it grabs the header from the first package and the footer from the second package another, while also ignoring the footer from the second package. Let me know what you think.

**Comment by lukekarrys** [comment]
I didn't realize I left the tests in a failing state. Just pushed a fixup that should be passing now.

**Review by chingor13 — APPROVED** [review]
Thanks!

**Pull request merged**
