### PR TITLE
fix: `findFilesByfilename` respects `path` option

### LINKED ISSUE #664: Python releaser not finding version.py with path option
We have a python project under `sdk-codegen/python` in a [monorepo](https://github.com/looker-open-source/sdk-codegen) (e.g. `sdk-codegen/python/setup.py`, `sdk-codegen/python/looker_sdk/version.py`) When I specify `path: python` in the action config I see a log error something like: "cannot find `python/python/looker_sdk/version.py`". Consequently our `python/looker_sdk/version.py` file is not updated.

It seems like the combination of `this.gh.findFilesByFilename` + `this.addPath` when `this.path` is defined [here](https://github.com/googleapis/release-please/blob/9ba60ee3f8f3bfc9c0dee3180dce3b16386aa1b1/src/releasers/python.ts#L120) produces an extra path prefix

I can take a stab at fixing it but not sure what the best solution is:
1. s/`path: this.addPath(path)`/`path: path`/ in the [python releaser](https://github.com/googleapis/release-please/blob/9ba60ee3f8f3bfc9c0dee3180dce3b16386aa1b1/src/releasers/python.ts#L120)
2. try to build some logic detecting `this.path` already in `file` in [`addPath`](https://github.com/googleapis/release-please/blob/9ba60ee3f8f3bfc9c0dee3180dce3b16386aa1b1/src/release-pr.ts#L324) (seems error prone)
3. add a `prefix?: string` parameter to [`findFilesByFilename`](https://github.com/googleapis/release-please/blob/9ba60ee3f8f3bfc9c0dee3180dce3b16386aa1b1/src/github.ts#L1001) and return the results relative to that path prefix?

### PR DESCRIPTION
**Pull request by joeldodge79**
scope code search to `path` and return paths relative to `path`.
update python releaser to call `findFilesByfilename` appropriately.

Fixes #664

### CODE REVIEW

**Comment by joeldodge79** [comment]
I wasn't quite up to adding a `test/releasers/python.ts` so codecov nailed me :-( I'd be happy to augment a test file if someone else starts it (I looked briefly at `test/releasers/node.ts` and decided I didn't have the time to invest in figuring it out/porting it for the python releaser), at least not before getting buy-in on this solution.

**Comment by bcoe** [comment]
@joeldodge79 I'm on a vacation for the next few days, very much appreciate the patch, will look soon.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@joeldodge79 this looks like a good fix to me 👍

**Comment by joeldodge79** [comment]
@bcoe sorry for the lag, I was completely unplugged for the past two weeks. I just rebased the branch. There's still the codecov issue for `test/releasers/python.ts` ... ok to let slide for now?

**Review by bcoe — APPROVED** [review]

**Pull request merged**
