### PR TITLE
feat: Introduce `componentNoSpace` parameter (Removes whitespace character from `${component}` title pattern) 

### LINKED ISSUE #1626: Provide `${component}` without whitespace of the beginning
Hi there, and thank you for maintaining the great package.

 **Is your feature request related to a problem? Please describe.**

Related to https://github.com/googleapis/release-please/issues/1623.

I want to use `${component}` as the scope of the commit message in `pull-request-title-pattern`.
e.g. `chore(${component}): release ${version}`

However the `${component}` contains whitespace at the beginning of it.

 **Describe the solution you'd like**

Remove whitespace of `${component}`

 **Describe alternatives you've considered**

Provide another template value that represents a component.

 **Additional context**

The whitespace is added in:

https://github.com/googleapis/release-please/blob/3169b4331ddad030a528cfc4003b5fef04ca8588/src/util/pull-request-title.ts#L159

and parsed in:

https://github.com/googleapis/release-please/blob/3169b4331ddad030a528cfc4003b5fef04ca8588/src/util/pull-request-title.ts#L48

### PR DESCRIPTION
**Pull request by Kiruyuto**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1626  🦕
# 
Introduces new parameter (`componentNoSpace`) which removes ` ` (space) character from `component` effectively allowing to use component as a scope or in any other "complex" scenario, eg.:
```json
"pull-request-title-pattern": "chore(${component}): ${version}"
```
Prior to this change attempting to do so resulted in this kind of behaviour
image

### CODE REVIEW

**Comment by simonostendorf** [comment]
I would be interested that this PR will be merged. What else needs to happen for that?

**Comment by Kiruyuto** [comment]
> I would be interested that this PR will be merged. What else needs to happen for that?

A stroke of luck that some maintainer sees this PR perhaps? I bet folks at google are busy but given the fact that last non-automated commit was made over 3 months ago it doesn't bode well

**Review by chingor13 — CHANGES_REQUESTED** [review]
Thank you for this, it will potentially visibly break users and disrupt parsing as the title does hold data for release-please.

Can we introduce a new template parameter (e.g. `componentNoSpace`) and handle both? In the next major version, we can "fix" this by making the breaking change.

**Comment by Kiruyuto** [comment]
Hey, 
As per your instructions, I added a new parameter, so it shouldn't mess up existing configurations, pipelines and whatnot.
Although I quickly tested the change, I might have missed a scenario where it might break up a thing or two, so lmk if you come up with something.

I've also tested it in a live repo, which you can see there:
Config file: https://github.com/Kiruyuto/rp-test/blob/master/release-please-config.json 
PRs: https://github.com/Kiruyuto/rp-test/pulls

Below are the commands I used to bootstrap and test that repo
<details>
  <summary>CLI commands</summary>

```bash
release-please bootstrap --token=[REDACTED] --repo-url=Kiruyuto/rp-test --release-type=node
```

```bash
npm run compile && node build/src/bin/release-please.js release-pr --token=[REDACTED] --repo-url=Kiruyuto/rp-test
```
  
</details>

**Review by chingor13 — APPROVED** [review]

**Pull request merged**
