### PR TITLE
fix: support-node-workspace-plugin-prerelease

### LINKED ISSUE #2248: Node-Workspaces plugin doesn't obey pre-release versioning strategy
Thanks for stopping by to let us know something could be better!

Please provide the following details.

#### Environment details

Github actions via `https://github.com/google-github-actions/release-please-action@v4`

#### Steps to reproduce

  1. Create a node root package inside of a GitHub repo
  2. Create two workspaces under that package called `@test/package-1` and `@test/package-2` at `packages/package-1` and `packages/package-2`, respectively
  3. Add a dependency on `@test/package-1` to `@test/package-2`
  4. Bootstrap `release-please` and add both packages to the config file with the following config: 
  ```
  {
      "versioning": "prerelease",
      "prerelease": true,
      "prerelease-type": "alpha"
  }
  ```
5. Configure the repo to use `release-please-action@v4` on `main` as described by (https://github.com/google-github-actions/release-please-action)
6. Update a file in `@test/package-1` to trigger a release PR creation
7. Notice that only `@test/package-1` has a pre-release version, `@test/package-2` has an updated but _not_ pre-release version. 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by Animalmix55**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #2248 🦕

### CODE REVIEW

**Comment by Animalmix55** [comment]
@chingor13 tested and validated using my local branch of https://github.com/Seekr-io/release-please-action

**Comment by tada5hi** [comment]
@Animalmix55 shouldn't the version be incremented to `x.x.x-beta.x` instead of `x.x.x-beta` ?

**Comment by Animalmix55** [comment]
> @Animalmix55 shouldn't the version be incremented to `x.x.x-beta.x` instead of `x.x.x-beta` ?

The initial prerelease comes with no .#, subsequent prereleases begin appending and iterating the .#.

**Review by niieani — APPROVED** [review]
Looks good. Hope this gets merged!

**Comment by ianpilipski-pf** [comment]
I'm also interested in this fix, is there any way to get it approved/merged?

**Review by chingor13 — APPROVED** [review]

**Comment by chingor13** [comment]
I need to be able to rebase/update from main to merge this. Can you either rebase/merge from main or enable the "Maintainer may modify" checkbox?

**Review by Mahki0412 — COMMENTED** [review]
$KYLEMITCHELLCOLEMAN CASH APP

**Pull request merged**
