### PR TITLE
feat: Update linked packages in package-lock.json

### PR DESCRIPTION
**Pull request by padaszewski**
Hi, I'm making a start for #1842 as this is very important for me.
I'm not fully into the code and this is just the starting point in my opinion.
Would love if someone could assist on this one!

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Addresses #1842 🦕

### CODE REVIEW

**Comment by padaszewski** [comment]
Updated CLA

**Comment by padaszewski** [comment]
This should be the right direction, but I'm still struggling with the test. Any help would be greatly appreciated!

**Review by chingor13 — CHANGES_REQUESTED** [review]
Please add tests to ensure we don't regress.

> I'm still struggling with the test

To test, you can run:

* `npm i`
* `npm t`

If you don't have node available, you can run this in a stock GitHub Codespace (IIRC, node 19 is installed which should suffice).

As for the contents of the test, you can probably:
1. augment an existing node-workspace test to ensure that it has an update for the package-lock.json file
2. add a test to the package-lock-json updater to ensure it updates multiple versions

**Comment by padaszewski** [comment]
Sorry, I have currently no time to get back to this, could anyone continue on that one?

**Pull request closed without merging**
