### PR TITLE
feat(python): support packagename/__init__.py without pyproject.toml

### LINKED ISSUE #1025: Support packagename/__init__.py irrespective of pyproject.toml
**Is your feature request related to a problem? Please describe.**

Supporting `<projectname>/__init__.py` is nice, but it only happens if there is a `pyproject.toml` (and it's "valid" -- the "validity" is something debatable but let's not get to that here). However the two are not really related/dependent, so it'd be great if the mentioned replacement would happen unconditionally.

 **Describe the solution you'd like**

Version in `<projectname>/__init__.py` always updated, if there is one.

 **Describe alternatives you've considered**

-

 **Additional context**

-

### PR DESCRIPTION
**Pull request by scop**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1025 (eventually)

Some first pseudocodelike steps to fixing #1025. Untested.

### CODE REVIEW

**Review by chingor13 — CHANGES_REQUESTED** [review]
This looks like a good start, but we need to adjust the tests accordingly and make sure we have a test case for the new functionality so we don't regress in the future.

**Comment by scop** [comment]
Sure. I'm not sure when/if I'll be taking this further, would appreciate a lot if someone who knows their way around release-please internals would finish it.

**Comment by bcoe** [comment]
@Mesteery if you have the cycles, could you help with this review, what was the reasoning for not updating `__init__.py` if there's no `pyproject.toml` file?

**Comment by Mesteery** [comment]
There is no reason for it. I added it with pyproject and didn't think of generalizing it for the rest.

**Review by chingor13 — APPROVED** [review]

**Pull request merged**
