### PR TITLE
feat: allow configuring simple strategy version file

### LINKED ISSUE #921: Simple release type: support `version-file` config option
**Is your feature request related to a problem? Please describe.**

I would like to use the config `version-file` for resolving custom `version.txt` files.

 **Describe the solution you'd like**

Have the Simple Releaser utilise the existing `version-file` configuration option to determine the location and filename of the file to hold the version number.

 **Describe alternatives you've considered**

NA

 **Additional context**

I believe this is the line in the repo to change https://github.com/googleapis/release-please/blob/0e5a2e09f509385b9b0caf3e32507ea296d3902f/src/releasers/simple.ts#L42

A repo I wish to use release-please on already has a `VERSION` file for maintaining the release version.

### PR DESCRIPTION
**Pull request by chingor13**
Fixes #921

### CODE REVIEW

**Comment by goatwu1993** [comment]
Any chance simple strategy to take a list of string and use ["version.txt"] as default values?

**Comment by goatwu1993** [comment]
please ignore me. Off topic.
> Any chance simple strategy to take a list of string and use ["version.txt"] as default values?

**Review by bcoe — COMMENTED** [review]
Thinking outloud, could the `versionFile` be a `JSON` file, and if so we take a key to update?

**Comment by axieum** [comment]
Perhaps the generic updaters could take a replacement `method`, e.g.

```jsonc
{
  "extra-files": [
    {
      "path": "version.json",
      "method": "regex",
      "version": ["\"version\": \"(.+?)\""], // arg for full version
      "minor": ["\"minor\": \"(.+?)\""] // arg for minor, can add more for major, patch, build, etc.
    },
    {
      "path": "some.txt",
      "method": "annotation" // optional/default
    },
    {
      "path": "other.json",
      "method": "json",
      "major": "version.items[2].major" // arg for major
  ]
}
```

I'm not sure how this would be set on the CLI though if wanting to allow configuration through that as well?

**Comment by chingor13** [comment]
> Perhaps the generic updaters (#1157) could take a replacement `method`, e.g.
> 
> ```js
> {
>   "extra-files": [
>     {
>       "path": "version.json",
>       "method": "regex",
>       "version": ["\"version\": \"(.+?)\""], // arg for full version
>       "minor": ["\"minor\": \"(.+?)\""] // arg for minor, can add more for major, patch, build, etc.
>     },
>     {
>       "path": "some.txt",
>       "method": "annotation" // optional/default
>     },
>     {
>       "path": "other.json",
>       "method": "json",
>       "major": "version.items[2].major" // arg for major
>   ]
> }
> ```
> 
> I'm not sure how this would be set on the CLI though if wanting to allow configuration through that as well?

> Thinking outloud, could the `versionFile` be a `JSON` file, and if so we take a key to update?

I think the issue both of you are describing is more related to #1180 than this fix. The `versionFile` here is a simple text file that only contains the version number.

**Review by bcoe — APPROVED** [review]

**Pull request merged**
