### PR TITLE
Revert "fix(github-release): private repo not found error"

### PR DESCRIPTION
**Pull request by bcoe**
Refs: https://github.com/googleapis/repo-automation-bots/pull/2334 this change appears to cause issues for some of the releasers.

Reverts googleapis/release-please#982

### CODE REVIEW

**Review by chingor13 — APPROVED** [review]

**Comment by bcoe** [comment]
@abeMedia with this update the PathNotFound error started throwing for files that are considered optional, such as `package-lock.json`.

**Comment by bcoe** [comment]
@abeMedia I believe the problem is that PathNotFound does not itself have a `code = 404`.

If it were to have a code of `404`, we would not need to update that test adding an additional `nock` test, I don't believe.

**Comment by abeMedia** [comment]
Ah damn! Before it was throwing an error at the same place so I guess the error handling just needs to be updated in some places to deal with the new one. Gonna get on it right away.

**Comment by abeMedia** [comment]
> @abeMedia I believe the problem is that PathNotFound does not itself have a `code = 404`.
> 
> If it were to have a code of `404`, we would not need to update that test adding an additional `nock` test, I don't believe.

Thanks for the heads-up. Will test that!

**Comment by abeMedia** [comment]
Sorry something came up yesterday. Will do another PR over the weekend though.

**Pull request merged**
