### PR TITLE
feat: add root package-lock.json support

### LINKED ISSUE #1842: Update versions of linked packages in package-lock.json to match package.json
Related to https://github.com/googleapis/release-please/issues/464

 **Is your feature request related to a problem? Please describe.**
Let's consider following scenario:
modules
If there is an update for one of the modules A,B,C then the corresponding `package-lock.json` will be updated. However, if I update the CoreModule, then the other modules will also be updated (`node-modules` plugin), but the version of the CoreModule will not be updated in the `package-lock.json` of the other modules. After releasing it is necessary to run `npm install` (which causes a change in the module dir and may cause unwanted version updates in the future). 
 **Describe the solution you'd like**
The version of a submodule is updated in the `package-lock.json` file of the module that depends on it (which also gets a patch update because of the `node-modules` plugin).
 **Describe alternatives you've considered**
No alternative considered.

### LINKED ISSUE #2161: Node Monorepo - Root package-lock.json
#### Environment details

  - OS: Ubunutu 22.04.3
  - Node.js version: 18.18.0
  - npm version: 9.8.1
  - `release-please` version:  16.4.0

#### Steps to reproduce

  1. create a nodejs/npm monorepo
  2. create release please manifest + config
  3. inspect pull request of release please bot

The problem is that release-please only tries to update the lock file in the local package folder (e.g. packages/package-a/package-lock.json), but not the root lock file.

In the following pull request https://github.com/authup/authup/pull/1566/files, for example, I would assume that the version of the respective package that is to be updated is also updated in the root package-lock.json file

### PR DESCRIPTION
**Pull request by tada5hi**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #2161 
Fixes #1842

### CODE REVIEW

**Review by chingor13 — COMMENTED** [review]
Rather than explicitly adding a check for a root `package-lock.json`, would it work if the `node-workspace` plugin respected the `considerAllArtifacts` option that other `workspace` plugins can use?

This option tells the plugin to scan for all "artifacts" (e.g. paths that have a `package.json`) even if they are undeclared as paths in the `release-please-config.json`. When building the dependency graph of artifacts that affect each other, the plugin would find the root `package.json` and create updates for it and its related `package-lock.json`.

**Comment by tada5hi** [comment]
@chingor13 I am unsure, as far as I can tell with my knowledge so far, I would say that this is not the case. 

Another problem is that the workspace packages are not (necessarily) part of the root package.json file, but only part of the package-lock.json file. For example, the [docs](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#releasing-root-path-of-library-) describe a scenario in which the root package is also published and references parts of the workspace packages. However, in most cases this is not the case, as the root package should also be published.

**Comment by blaine-arcjet** [comment]
@chingor13 I just ran into this same problem. What would it take to get this across the finish line?

**Comment by tada5hi** [comment]
@chingor13 ?

**Review by chingor13 — APPROVED** [review]

**Pull request merged**
