### PR TITLE
feat: add arbitrary file updater

### LINKED ISSUE #1171: Add ability to update arbitrary JSON files
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**

I would like to have an arbitrary file updater.

This updater should be able to replace content from a version to another, without any extra regex.

For example, replace all 0.1.0 to 0.2.0 in a file

### PR DESCRIPTION
**Pull request by goatwu1993**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/release-please/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1171 🦕

### CODE REVIEW

**Comment by chingor13** [comment]
Thanks for building this.

The reason we didn't build a version replacer like this is that it can replace content in unintended places. If you happen to have another string in the file that matches the previous version (perhaps a version for a different dependency), it will update that version as well. This is probably an ok risk for most files, but the edge cases will catch people off guard.

**Comment by goatwu1993** [comment]
Yeah i totally agree, and I just found the pr which provide adhoc annotation, which will probably solve my use cases.

However, a json file, AFAIU, does not allow annotating or commenting. 

I believe arbitrary updater make sense in these worst case senario? Please correct me if I am wrong

**Comment by bcoe** [comment]
@goatwu1993 @chingor13 it would be interesting to figure out how to solve the `.json` file use case.

**Comment by goatwu1993** [comment]
I guess JMESPath, jq or similar JSON Path parsing library should work for json.

I will close this PR since I get the idea that an updater should have the least parsing logic to avoid unintentional content change.

**Pull request closed without merging**
