### PR TITLE
fix: manifest config should allow overriding labels

### LINKED ISSUE #1302: Add labels to manifest options when parsing config
I'd like to change the default **"autorelease: pending"** GitHub label when using the release-please action. However, labels are not included in manifest options when the config file is parsed. [On these lines](https://github.com/googleapis/release-please/blob/main/src/manifest.ts#L973), `labels` and `releaseLabels` properties are missing.

### PR DESCRIPTION
**Pull request by psirenny**
Add labels to manifest options when parsing config.

Resolves #1302

### CODE REVIEW

**Comment by chingor13** [comment]
Thanks, you'll have to sign the CLA (which is linked from the failing check: https://github.com/googleapis/release-please/pull/1303/checks?check_run_id=5206383733) before we can accept a PR

**Comment by psirenny** [comment]
Thanks, I just signed the CLA.

**Review by chingor13 — CHANGES_REQUESTED** [review]
Thanks for this!

Looks like the linter is failing. Formatting can be fixed by running `npm run fix`.

Additionally, would you be able to add a test for this to ensure we don't regress in the future? Something like https://github.com/googleapis/release-please/blob/main/test/manifest.ts#L261-L290 which stubs a manifest config and checks the configuration of the manifest.

**Comment by psirenny** [comment]
@chingor13 thanks for your patience. I corrected the formatting and added the missing unit test.

**Review by chingor13 — APPROVED** [review]

**Review by chingor13 — APPROVED** [review]

**Pull request merged**
