### PR TITLE
docs: tweak typo in the spelling of prerelease

### PR DESCRIPTION
**Pull request by dbirks**
Just fixing a typo of `prerelese` to `prerelease`. Let me know if I should still make an issue first. Thanks for working on this project!

### CODE REVIEW

**Review by chingor13 — APPROVED** [review]
Thanks

**Review by chingor13 — CHANGES_REQUESTED** [review]
Apologies, you'll need to fix the CLA agreement

**Comment by dbirks** [comment]
Ah thank you, just force-pushed to get my email to match the one I used to just now sign the CLA... and looks like the check passed!

**Review by chingor13 — APPROVED** [review]
Thanks!

**Pull request merged**
